basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)  
a = set('abracadabra')
b = set('alacazam')
print("set a: ")
print(a)
print("a-b: ")
print(a-b)
print("a|b ")
print(a|b) 
print(a&b)
print(a^b)
